import React, { useState, useEffect, useRef } from 'react';
import { Heart, Stars, Globe, RefreshCcw, Sparkles, Loader2, ChevronRight } from 'lucide-react';
import imgPast from './assets/IMG_4580.JPG';
import imgFuture from './assets/IMG_5150.jpg';

// Configuración de la API
const apiKey = import.meta.env.VITE_GEMINI_API_KEY || "";
const modelName = "gemini-2.5-flash-preview-09-2025";

const App = () => {
  const [language, setLanguage] = useState(null);
  const [currentScene, setCurrentScene] = useState(0);
  const [aiAdvice, setAiAdvice] = useState("");
  const [isLoadingAi, setIsLoadingAi] = useState(false);
  const [hearts, setHearts] = useState([]);

  // Traducciones
  const translations = {
    es: {
      "intro-title": "Once años de nosotros",
      "intro-text": "Esta no es una historia de cuentos de hadas. Es una historia de verdad, de tiempo y de elección.",
      "date1-title": "El primer latido",
      "date1-text": <>Aquel 26 de diciembre de 2014, sin saberlo, algo cambió para <span className='highlight-always'>SIEMPRE</span>. Me enamoré.</>,
      "date2-title": "La promesa silenciosa",
      "date2-text": "Dos días después, el 28 de diciembre, decidimos intentarlo. Fue el inicio de un viaje con rumbo a lo desconocido.",
      "date3-title": "Caminando juntos",
      "date3-text": <>El 23 de mayo de 2020, en medio de un mundo incierto, nos dijimos 'sí' para <span className='highlight-always'>SIEMPRE</span>.</>,
      "struggle-title": "La imperfección hermosa",
      "struggle-text": "No ha sido un camino fácil. Hemos tenido tormentas y días grises. Pero cada cicatriz nos ha hecho más reales.",
      "now-title": "Aún aquí",
      "now-text": "11 años después, sin arrepentimientos. Seguimos juntos, construyendo sobre lo vivido.",
      "ai-title": "Un pensamiento para el camino...",
      "ai-disclaimer": "Este consejo fue generado aleatoriamente por una inteligencia artificial basada en el amor y la reflexión.",
      "btn-next": "Continuar",
      "btn-final": "Mirar hacia el futuro",
      "btn-restart": "Volver a empezar",
      "loading-ai": "Consultando a las estrellas...",
      "choose-lang": "Elegir Idioma"
    },
    en: {
      "intro-title": "Eleven Years of Us",
      "intro-text": "This isn't a fairy tale. It's a story of truth, time, and choice.",
      "date1-title": "The First Heartbeat",
      "date1-text": <>That December 26, 2014, without knowing it, something changed <span className='highlight-always'>FOREVER</span>. I fell in love.</>,
      "date2-title": "The Silent Promise",
      "date2-text": "Two days later, on December 28, we decided to try. It was the start of a journey into the unknown.",
      "date3-title": "Walking Together",
      "date3-text": <>On May 23, 2020, amidst an uncertain world, we said 'I do' <span className='highlight-always'>FOREVER</span>.</>,
      "struggle-title": "Beautiful Imperfection",
      "struggle-text": "It hasn't been an easy road. We've had storms and gray days. But every scar has made us more real.",
      "now-title": "Still Here",
      "now-text": "11 years later, no regrets. We are still together, building on everything we've lived.",
      "ai-title": "A thought for the road...",
      "ai-disclaimer": "This advice was randomly generated by an artificial intelligence based on love and reflection.",
      "btn-next": "Continue",
      "btn-final": "Look into the future",
      "btn-restart": "Start Over",
      "loading-ai": "Consulting the stars...",
      "choose-lang": "Choose Language"
    }
  };

  const t = (key) => language ? translations[language][key] : "";

  // Efecto para corazones flotantes
  useEffect(() => {
    const newHearts = Array.from({ length: 15 }).map((_, i) => ({
      id: i,
      left: Math.random() * 100,
      delay: Math.random() * 15,
      size: Math.random() * 1 + 0.5,
      icon: [Heart, Stars, Sparkles][Math.floor(Math.random() * 3)]
    }));
    setHearts(newHearts);
  }, []);

  // Llamada a Gemini con backoff
  const fetchLoveAdvice = async (lang) => {
    setIsLoadingAi(true);
    const prompt = lang === 'es' 
      ? "Escribe un consejo corto (máximo 2 frases), poético y profundo sobre cómo mantener vivo un amor de 11 años que ha superado dificultades reales. No uses clichés exagerados."
      : "Write a short (max 2 sentences), poetic and deep advice on how to keep an 11-year love alive that has overcome real difficulties. Avoid cheesy clichés.";

    const systemPrompt = "Eres un poeta experto en sabiduría emocional y relaciones humanas duraderas.";

    const makeRequest = async (retries = 0) => {
      try {
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            systemInstruction: { parts: [{ text: systemPrompt }] }
          })
        });

        if (!response.ok) throw new Error();
        const data = await response.json();
        setAiAdvice(data.candidates?.[0]?.content?.parts?.[0]?.text || "Love is the daily choice to stay.");
      } catch (error) {
        if (retries < 5) {
          setTimeout(() => makeRequest(retries + 1), Math.pow(2, retries) * 1000);
        } else {
          setAiAdvice(lang === 'es' ? "El amor verdadero no es un destino, sino la forma en que caminamos juntos." : "True love is not a destination, but the way we walk together.");
        }
      } finally {
        setIsLoadingAi(false);
      }
    };

    makeRequest();
  };

  const handleNext = () => {
    const next = currentScene + 1;
    setCurrentScene(next);
    if (next === 7) fetchLoveAdvice(language);
  };

  const handleRestart = () => {
    setCurrentScene(0);
    setLanguage(null);
    setAiAdvice("");
  };

  const MemoryFrame = ({ type = "past", emoji = "💑", image = null }) => (
    <div className={`memory-frame ${type === 'future' ? 'future' : ''} bg-white border-8 border-white rounded-[24px] shadow-xl overflow-hidden my-6 mx-auto w-full max-w-[300px] aspect-[3/4] flex items-center justify-center relative`}>
      {image ? (
        <img src={image} alt="Memory" className="w-full h-full object-cover" />
      ) : (
        <span className="text-6xl opacity-40 animate-breathe">{emoji}</span>
      )}
      <div className="absolute bottom-4 text-[10px] tracking-widest text-pink-900/30">✦</div>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#fffcfc] text-[#333] relative overflow-hidden font-sans">
      {/* Background */}
      <div className="fixed inset-0 bg-gradient-to-br from-[#fff5f5] to-[#fce4ec] -z-10" />
      
      {/* Floating Elements */}
      <div className="fixed inset-0 pointer-events-none z-0">
        {hearts.map(h => (
          <div 
            key={h.id}
            className="absolute animate-float opacity-10 text-pink-800"
            style={{ 
              left: `${h.left}%`, 
              animationDelay: `${h.delay}s`,
              fontSize: `${h.size}rem`,
              bottom: '-5%'
            }}
          >
            <h.icon size={24 * h.size} />
          </div>
        ))}
      </div>

      <main className="relative z-10 max-w-lg mx-auto px-6 flex flex-col items-center justify-center min-h-screen text-center">
        
        {/* ESCENA 0: IDIOMA */}
        {currentScene === 0 && (
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-1000">
            <Globe className="mx-auto mb-6 text-pink-800 opacity-50" size={40} />
            <h1 className="text-3xl font-serif mb-8">Elegir Idioma / Language</h1>
            <div className="flex flex-col gap-4 w-64">
              <button 
                onClick={() => { setLanguage('es'); setCurrentScene(1); }}
                className="btn-primary"
              >
                🇪🇸 Español
              </button>
              <button 
                onClick={() => { setLanguage('en'); setCurrentScene(1); }}
                className="btn-primary"
              >
                🇺🇸 English
              </button>
            </div>
          </div>
        )}

        {/* ESCENA 1: INTRO */}
        {currentScene === 1 && (
          <div className="animate-in fade-in duration-1000">
            <h2 className="text-4xl font-serif mb-2">{t('intro-title')}</h2>
            <MemoryFrame image={imgPast} />
            <p className="text-lg font-light leading-relaxed mb-8">{t('intro-text')}</p>
            <button onClick={handleNext} className="btn-primary flex items-center gap-2 mx-auto">
              {t('btn-next')} <ChevronRight size={16} />
            </button>
          </div>
        )}

        {/* ESCENAS DE TIMELINE (2, 3, 4) */}
        {[2, 3, 4].includes(currentScene) && (
          <div className="animate-in fade-in duration-1000">
            <span className="text-xs tracking-[0.3em] font-semibold text-pink-900/60 uppercase mb-4 block">
              {currentScene === 2 ? '26.12.2014' : currentScene === 3 ? '28.12.2014' : '23.05.2020'}
            </span>
            <h2 className="text-3xl font-serif mb-6">
              {t(`date${currentScene - 1}-title`)}
            </h2>
            <p className="text-lg font-light leading-relaxed max-w-sm mb-8">
              {t(`date${currentScene - 1}-text`)}
            </p>
            <button onClick={handleNext} className="btn-primary mx-auto">
              {t('btn-next')}
            </button>
          </div>
        )}

        {/* ESCENA 5: DIFICULTADES */}
        {currentScene === 5 && (
          <div className="animate-in fade-in duration-1000">
            <h2 className="text-3xl font-serif mb-6">{t('struggle-title')}</h2>
            <p className="text-lg font-light italic leading-relaxed max-w-sm mb-8">
              {t('struggle-text')}
            </p>
            <button onClick={handleNext} className="btn-primary mx-auto">
              {t('btn-next')}
            </button>
          </div>
        )}

        {/* ESCENA 6: ACTUALIDAD */}
        {currentScene === 6 && (
          <div className="animate-in fade-in duration-1000">
            <h2 className="text-4xl font-serif mb-2">{t('now-title')}</h2>
            <MemoryFrame type="future" image={imgFuture} />
            <p className="text-lg font-light leading-relaxed mb-8">{t('now-text')}</p>
            <button onClick={handleNext} className="btn-primary mx-auto">
              {t('btn-final')}
            </button>
          </div>
        )}

        {/* ESCENA 7: AI ADVICE */}
        {currentScene === 7 && (
          <div className="animate-in fade-in duration-1000">
            <Stars className="mx-auto mb-6 text-pink-800 opacity-40" size={32} />
            <h2 className="text-2xl font-serif mb-8">{t('ai-title')}</h2>
            
            <div className="min-h-[140px] flex items-center justify-center mb-8">
              {isLoadingAi ? (
                <div className="flex flex-col items-center gap-3 opacity-50">
                  <Loader2 className="animate-spin" />
                  <span className="text-sm tracking-widest uppercase">{t('loading-ai')}</span>
                </div>
              ) : (
                <p className="text-xl font-light italic leading-relaxed px-4 text-pink-900">
                  {aiAdvice}
                </p>
              )}
            </div>

            <p className="text-[10px] text-gray-400 uppercase tracking-widest max-w-[250px] mx-auto mb-10 leading-loose">
              {t('ai-disclaimer')}
            </p>

            <button onClick={handleRestart} className="btn-primary flex items-center gap-2 mx-auto">
              <RefreshCcw size={14} /> {t('btn-restart')}
            </button>
          </div>
        )}

      </main>

      <style dangerouslySetInnerHTML={{ __html: `
        .btn-primary {
          @apply px-8 py-3 border border-pink-900/30 text-pink-900 rounded-full text-xs uppercase tracking-widest 
                 transition-all duration-500 hover:bg-pink-900 hover:text-white hover:shadow-lg active:scale-95;
        }

        .highlight-always {
          font-weight: 800;
          color: #880e4f;
          display: inline-block;
          animation: pulseAlways 2s infinite ease-in-out;
        }

        @keyframes pulseAlways {
          0%, 100% { transform: scale(1); text-shadow: 0 0 5px rgba(136, 14, 79, 0.1); }
          50% { transform: scale(1.1); text-shadow: 0 0 15px rgba(136, 14, 79, 0.4); color: #b71c1c; }
        }

        @keyframes float {
          0% { transform: translateY(0) rotate(0deg); opacity: 0; }
          10% { opacity: 0.15; }
          90% { opacity: 0.15; }
          100% { transform: translateY(-110vh) rotate(360deg); opacity: 0; }
        }

        .animate-float {
          animation: float 15s infinite linear;
        }

        @keyframes breathe {
          0%, 100% { transform: scale(1); opacity: 0.4; }
          50% { transform: scale(1.1); opacity: 0.6; }
        }

        .animate-breathe {
          animation: breathe 4s infinite ease-in-out;
        }

        .future {
          background: linear-gradient(135deg, #e8f0ff 0%, #fef6e4 100%) !important;
        }
      `}} />
    </div>
  );
};

export default App;